# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-24 08:32
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
