# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170523_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section',
            field=models.CharField(max_length=50),
        ),
    ]
