# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='readtime',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
