# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20170526_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Section'),
        ),
    ]
