# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_post_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hits', models.BigIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
