# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20170708_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='name',
            field=models.CharField(default='sarcblog', max_length=20),
        ),
        migrations.AlterField(
            model_name='stats',
            name='hits',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
