# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20170708_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='hits',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
