# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20170708_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('from_email', models.EmailField(max_length=32)),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
