# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-28 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20170708_1259'),
        ('posts', '0020_auto_20180128_1313'),
    ]

    operations = [
    ]
